### ISSUE TITLE
Showing INCOMPATIBLE on Gnome Extensions

### ISSUE THREAD

**Issue by ikbal-nayem** [dgvai/maccymenu-gnome-shell-ext#7]
**Cannot install on Ubuntu version 22.04.2**
![image](https://github.com/dgvai/maccymenu-gnome-shell-ext/assets/31121811/4bb1ceb9-d4a4-41f2-82c7-0eef7b40f785)

My Gnome version is 42.5
![image](https://github.com/dgvai/maccymenu-gnome-shell-ext/assets/31121811/1b8a7544-0258-43b1-9fd9-03afd2bb5164)

**Comment by dgvai** [comment]
HI, the support for GNOME 42.x was added to Version 8, please get the latest version of the extension. #6
